-- create pms database
create database pms;

-- create product table
CREATE TABLE `pms`.`product` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `PRICE` DECIMAL(10,2) NOT NULL,
  `ACTIVE_STATUS` VARCHAR(20) NOT NULL,
  `CREATED_DATE_TIME` DATETIME NOT NULL,
  `UPDATED_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`));
